### ISSUE TITLE
Stompserver not working?

### ISSUE THREAD

**Issue by fastgar** [3zLabs/zKillboard#7]
Pls see ticket in wrong repo:
https://github.com/EVE-KILL/zKillboard/issues/313

But adress given by sn0opy also not working:
tcp://eve-kill.net:61613

zkb.log:
[message:protected] => Server is not responding
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /var/www/html/zKillboard/cli/cli_stompReceive.php
    [line:protected] => 56
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /var/www/html/zKillboard/cli/cli_stompReceive.php
                    [line] => 56
                    [function] => __construct
                    [class] => Stomp
                    [type] => ->
                    [args] => Array
                        (
                            [0] => tcp://eve-kill.net:61613
                            [1] => guest
                            [2] => guest
                        )

                )

**Comment by cvweiss** [comment]
Replied in referenced issue.
