### ISSUE TITLE
Corporation stats page is throwing an error.

### ISSUE THREAD

**Issue by nCrazed** [3zLabs/zKillboard#8]
## Error Message

> krsort() expects parameter 1 to be array, null given

## How to Reproduce

1. Go to any corporation's page
2. Click on the corporation's `Stats` link.
3. Get the error.

## Example

https://zkillboard.com/corporation/1000049/stats/

**Comment by cvweiss** [comment]
My apologies, was working on some new code that was left unfinished which caused this error
