### ISSUE TITLE
startTime and endTime are not handled correctly

### ISSUE THREAD

**Issue by Pulttl** [3zLabs/zKillboard#9]
It seems that startTime and endTime modifiers are not handled correctly when using the zKillboard API.  Could you confirm if this is my mistake or an actual issue?  For example, [#1](https://zkillboard.com/api/kills/orderDirection/asc/startTime/201201012333/solarSystemID/30003503/) returns kills from the beginning, ignoring startTime.  [#2](https://zkillboard.com/api/kills/orderDirection/asc/endTime/201201012333/solarSystemID/30003503/) (startTime is replaced with endTime) returns nothing.  This seems to be zkillboard.com specific at the moment; [#3](https://beta.eve-kill.net/api/kills/orderDirection/asc/startTime/201201012333/solarSystemID/30003503/) (Same as the first one except using beta.eve-kill.net) returns kills as I expect; zkillboard.com worked similarly until recently.

How do startTime and endTime work nowadays?  Do I need to use a new timestamp format?  Is this issue possibly related to 0064c8040a09b48dc9173d6547f98407501f3488?

Also I apologize for requesting the same URL repetitively.  My script got so confused by not receiving kills as it expected.  I shut it down after trying to adapt it to the new API results.

**Comment by cvweiss** [comment]
I rewrote some of the API code the other day, looks like there's a problem with startTime and endTime.  I'll check it out tonight.

**Comment by cvweiss** [comment]
This has been corrected.
